[build]
  publish = "dist" # The production build output folder for Vite

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"